/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package demo.glue.schema.registry.avro;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum unicorn_color {
  WHITE, RED, BLUE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"unicorn_color\",\"namespace\":\"demo.glue.schema.registry.avro\",\"symbols\":[\"WHITE\",\"RED\",\"BLUE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
