/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package demo.glue.schema.registry.avro;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum ModeOfPayment {
  CARD, CASH  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ModeOfPayment\",\"namespace\":\"demo.glue.schema.registry.avro\",\"symbols\":[\"CARD\",\"CASH\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
