/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package demo.glue.schema.registry.avro;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum UnicornPreferredColor {
  WHITE, BLACK, RED, BLUE, GREY  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"UnicornPreferredColor\",\"namespace\":\"demo.glue.schema.registry.avro\",\"symbols\":[\"WHITE\",\"BLACK\",\"RED\",\"BLUE\",\"GREY\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
